import { AuctionListing } from "@/types";

export const FEATURED_AUCTIONS: AuctionListing[] = [
    {
        id: "1",
        title: "BMW Sports M3 Package",
        year: 2023,
        mileage: "10,248 KM's",
        transmission: "Manual",
        fuelType: "Petrol",
        price: 2870000,
        rating: 9.2,
        image: "/images/cars/featured-placeholder.webp", // Using existing hero image as placeholder
        endTime: "2026-01-08T00:00:00", // Approx 2 days from now
        isLive: true,
        isFeatured: true,
    },
    {
        id: "2",
        title: "Toyota Yaris GR Sport",
        year: 2023,
        mileage: "5,000 KM's",
        transmission: "Manual",
        fuelType: "Petrol",
        price: 4500000,
        rating: 9.5,
        image: "/images/cars/featured-placeholder.webp",
        endTime: "2026-01-09T00:00:00",
        isLive: true,
        isFeatured: true,
    },
    {
        id: "3",
        title: "Honda Civic RS Turbo",
        year: 2022,
        mileage: "15,300 KM's",
        transmission: "Automatic",
        fuelType: "Petrol",
        price: 8200000,
        rating: 8.8,
        image: "/images/cars/featured-placeholder.webp",
        endTime: "2026-01-07T12:00:00",
        isLive: true,
        isFeatured: true,
    },
    {
        id: "4",
        title: "Audi e-tron GT",
        year: 2024,
        mileage: "1,200 KM's",
        transmission: "Automatic",
        fuelType: "Electric",
        price: 35000000,
        rating: 9.8,
        image: "/images/cars/featured-placeholder.webp",
        endTime: "2026-01-10T15:30:00",
        isLive: true,
        isFeatured: true,
    },
];
